### ISSUE TITLE
White screen after launch Minecraft 

### ISSUE THREAD

**Issue by mefiu45** [MinecraftHopper/MinecraftHopper#19]
I come with a problem when I turn on Minecraft the game window is white, I can click things and I hear sounds but I can't see because almost the entire window is white I have tried many ways to fix it from the Internet but rarely did not work. And I come here hoping that it can be fixed somehow.

https://paste.ubuntu.com/p/PtP8dCrGgS/ there is a link to my DirectX Diagnostics

**Comment by LordRalex** [comment]
Use our discord for help, not the website issues page.

https://discord.gg/58Sxm23
