### ISSUE TITLE
Change malwarebytes link to adwcleaner on Exit code -805306369 article

### ISSUE THREAD

**Issue by Greymagic27** [MinecraftHopper/MinecraftHopper#94]
ADWCleaner usually works for this exit code so the malwarebytes link should be changed to an adwcleaner one. Or possibly include both but ADW first?

**Comment by Southpaw1496** [comment]
Malwarebytes works on both Windows and Mac, and they generally catch the same stuff in my experience. Having said that, I'm not sure if the issue affects macOS, so there's that.

**Comment by Greymagic27** [comment]
True, but I was also thinking in terms of quickness. ADWCleaner can catch it and take <5 minutes. Malwarebytes scans everything and it's a proper install

**Comment by Southpaw1496** [comment]
A good point. I see the value of switching for ADWCleaner if the issue only affects Windows but if it doesn't I think it'll just make the instructions more complex to follow for people.

**Comment by Greymagic27** [comment]
> A good point. I see the value of switching for ADWCleaner if the issue only affects Windows but if it doesn't I think it'll just make the instructions more complex to follow for people.

Ah yes. I wasn't thinking about other OSs there. Could add it as the step above though? So it says run adwcleaner and below that says run Malwarebytes
